apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgerwriter
spec:
  selector:
    matchLabels:
      app: ledgerwriter
  template:
    metadata:
      labels:
        app: ledgerwriter
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: writer
        image: ledgerwriter
        env:
        - name: LEDGER_ADDR
          value: "redis-ledger"
        - name: LEDGER_PORT
          value: "6379"
        - name: LEDGER_STREAM
          value: "ledger"
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ledgerwriter
spec:
  type: ClusterIP
  selector:
    app: ledgerwriter
  ports:
  - name: http
    port: 8080
    targetPort: 8080
