apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgerwriter
spec:
  selector:
    matchLabels:
      app: ledgerwriter
  template:
    metadata:
      labels:
        app: ledgerwriter
    spec:
      terminationGracePeriodSeconds: 5
      volumes:
      - name: pub-key
        secret:
          secretName: bank-0-public-key
      containers:
      - name: writer
        image: ledgerwriter
        volumeMounts:
        - name: pub-key
          mountPath: /var/secrets/keys
        env:
        - name: PUB_KEY_PATH
          value: /var/secrets/keys/bank-0.pub
        # possible security issue?
        - name: BRANCH_ID
          value: '1234'
        - name: LEDGER_ADDR
          value: "redis-ledger"
        - name: LEDGER_PORT
          value: "6379"
        - name: LEDGER_STREAM
          value: "ledger"
        - name: UNCONF_ADDR
          value: "redis-unconfirmed"
        - name: UNCONF_PORT
          value: "6379"
        - name: UNCONF_STREAM
          value: "unconfirmed"
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
