apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgerwriter
spec:
  selector:
    matchLabels:
      app: ledgerwriter
  template:
    metadata:
      labels:
        app: ledgerwriter
    spec:
      terminationGracePeriodSeconds: 5
      initContainers:
      - name: init-db-ready
        image:  redis:alpine
        command: ['/bin/sh', '-c']
        args:
          - for i in {1..100}; do sleep 1; if redis-cli -h redis-ledger -p 6379 ping; then exit 0; fi; done; exit 1
      containers:
      - name: writer
        image: ledgerwriter
        env:
        - name: LEDGER_ADDR
          value: "redis-ledger"
        - name: LEDGER_PORT
          value: "6379"
        - name: LEDGER_STREAM
          value: "ledger"
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ledgerwriter
spec:
  type: ClusterIP
  selector:
    app: ledgerwriter
  ports:
  - name: http
    port: 8080
    targetPort: 8080
