apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgerwriter
spec:
  selector:
    matchLabels:
      app: ledgerwriter
  template:
    metadata:
      labels:
        app: ledgerwriter
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: writer
        image: ledgerwriter
        env:
        - name: BRANCH_ID
          valueFrom:
            configMapKeyRef:
              name: branch-info
              key: branch_id
        - name: LEDGER_ADDR
          value: "redis-ledger"
        - name: LEDGER_PORT
          value: "6379"
        - name: LEDGER_STREAM
          value: "ledger"
        - name: UNCONF_ADDR
          value: "redis-unconfirmed"
        - name: UNCONF_PORT
          value: "6379"
        - name: UNCONF_STREAM
          value: "unconfirmed"
        - name: PUBLIC_KEY_MANAGER_URI
          value: "public-key-manager:8080"
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
