# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokencreator
spec:
  selector:
    matchLabels:
      app: tokencreator
  template:
    metadata:
      labels:
        app: tokencreator
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: creator
        image: tokencreator
        volumeMounts:
        - name: privatekey
          mountPath: "/root/.ssh"
          readOnly: true
        env:
        - name: PORT
          value: "8080"
        - name: KEY_PATH
          value: "/root/.ssh/privatekey"
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
      volumes:
      - name: privatekey
        secret:
          secretName: jwt-key
          items:
          - key: jwtRS256.key
            path: privatekey
---
apiVersion: v1
kind: Service
metadata:
  name: tokencreator
spec:
  type: ClusterIP
  selector:
    app: tokencreator
  ports:
  - name: http
    port: 8080
    targetPort: 8080
